---
- hosts: dev
  become: True
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true
    - name: Upgrade all apt packages
      apt: upgrade=yes force_apt_get=yes
      become: true
    - name: install python-pip3
      apt:
        name: python3-pip #python-pip3
        update_cache: yes
        state: present
    - name: Install Python packages
      pip: name={{ item }}
      with_items:
      - psycopg2-binary
      become: true
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Run the container
      docker_container:
        name: hassan-app
        image: "hassanali70826/myapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8088:8088
