
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-k-deployment
  labels:
    app: myapp-k
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-k
  template:
    metadata:
      labels:
        app: myapp-k 
    spec:
      containers:
      - name: myapp-server
        image: hassanali70826/myapp:tagVersion
        ports:
        - containerPort: 8080     
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-k-service
spec:
  selector:
    app: myapp-k 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31110
